package entities;
// Generated Aug 23, 2017 10:05:46 AM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ordersdetail generated by hbm2java
 */
@Entity
@Table(name = "ordersdetail", catalog = "demo")
public class Ordersdetail implements java.io.Serializable {

	private OrdersdetailId id;
	private Orders orders;
	private Product product;
	private BigDecimal price;
	private int quantity;

	public Ordersdetail() {
	}

	public Ordersdetail(OrdersdetailId id, Orders orders, Product product, BigDecimal price, int quantity) {
		this.id = id;
		this.orders = orders;
		this.product = product;
		this.price = price;
		this.quantity = quantity;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productid", column = @Column(name = "productid", nullable = false)),
			@AttributeOverride(name = "ordersid", column = @Column(name = "ordersid", nullable = false)) })
	public OrdersdetailId getId() {
		return this.id;
	}

	public void setId(OrdersdetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ordersid", nullable = false, insertable = false, updatable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productid", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "price", nullable = false, precision = 10, scale = 1)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
